// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohiwfhazbbbswqrljzph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oaXdmaGF6YmJic3dxcmxqenBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNjgwNTIsImV4cCI6MjA2MTk0NDA1Mn0.xaEpbRH9GHj6V-S7ZxhYNItBF9vDYJylnMoNJrgGzf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);